# Generated by Django 3.2.15 on 2022-11-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_title', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Surname')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='Birthday')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('article', models.TextField(blank=True, verbose_name='Article')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('people_profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appmy.profession', verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
